name: correction
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  job_correction_CALLED:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'correction'
    runs-on: ubuntu-latest
    steps:
      - name: Github-Script
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
            
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: MIZOGUCHIKoki/ConfigFiles
          path: ConfigFiles
      - name: Copy files to current directory
        run: | 
          cp  ./ConfigFiles/tex_textlint/package.json ./
          cp  ./ConfigFiles/tex_textlint/.textlintrc.json ./
          cp  ./ConfigFiles/tex_textlint/package-lock.json ./
            
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Correct
        run: |
          npx textlint --fix articles/* books/*
      - name: Remove and restore useless files
        if: ${{ always() }}
        run: |
          git restore package.json package-lock.json
          rm -rf .textlintrc.json
      - name: Check changed files
        if: ${{ always() }}
        id: diffcheck
        run: |
          git diff >> diff.txt
          if [ -s diff.txt ];
          then
            echo "RESULT=1" >> $GITHUB_OUTPUT
          fi
          rm diff.txt
      - name: Commit to current branch
        if: ${{ always() && steps.diffcheck.outputs.RESULT == 1 }}
        run: |
          git branch -a
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Proofreading"
          git push
