name: run-textlint
on: 
  push:
    branches:
      - main
    paths:
      - '**/**.md'
  pull_request:
    paths:
      - '**/**.md'
  
jobs:
  job_textlint_MAIN:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Clone
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: MIZOGUCHIKoki/ConfigFiles
          path: ConfigFiles
      - name: Move files
        run: cp -a ./ConfigFiles/tex_textlint/. ./
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Run textlint
        run: |
            npx textlint -f checkstyle articles/* books/* >> ./textlint.xml
      - name: Report if textlint finds problems (main)
        if: ${{ failure() && github.ref_name == 'main' }}
        run: cat ./textlint.xml
      - name: Report if textlint finds problems (other branches)
        if: ${{ failure() && github.ref_name != 'main' }}
        run: |
            sudo apt-get install xsltproc libxml2-utils
            xmllint --format ./textlint.xml > ./ftextlint.xml
            sed 2i\<?xml-stylesheet\ type=text\/xsl\ href=./toHTML.xsl\ \?\> ./ftextlint.xml > ./ptextlint.xml
            sed -i 's/([^)]*)//g' ./ptextlint.xml
            sed -i 's/eslint.rules.//g' ./ptextlint.xml
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            xsltproc --output body.html ./toHTML.xsl ptextlint.xml
            cat body.html | sed "s/${pwd_esc}/:memo: ./g" >> ./.body.html
            gh pr comment --body-file ./.body.html "${URL}"      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
